### ISSUE TITLE
MottattMelding.isHarPayload returnerer true for meldinger uten payload

### ISSUE THREAD

**Issue by johnksv** [ks-no/fiks-io-klient-java#368]
**Nåværende oppførsel**
MottattMelding sin metode `isHarPayload` returnerer `true` for meldinger uten payload

**Steg for å reprodusere**
1. Sett opp en fiksio-klientog lag en meldingsrequest som du kan motta
2. Send melding via klienten med følgende metode: `fiksIoClient.sendWithoutPayload(meldingRequest);`
3. I mottaket returnerer `mottattMelding.isHarPayload` true

Hvis man videre forsøker å konsumere payloaden, feks `mottattMelding.getDekryptertZipStream().getNextEntry()`, vil man ende opp med å få `null` i retur samt at dette exceptionet/stack tracen logges:
```
no.ks.kryptering.KrypteringException: Dekryptering av forsendelsesdokumenter feilet
	at no.ks.kryptering.CMSKrypteringImpl.dekrypterData(CMSKrypteringImpl.java:156)
	at no.ks.kryptering.CMSKrypteringImpl.dekrypterData(CMSKrypteringImpl.java:144)
	at no.ks.fiks.io.asice.crypto.DecryptionStreamServiceImpl.decrypterStream(DecryptionStreamServiceImpl.java:15)
	at no.ks.fiks.io.asice.read.EncryptedAsicReaderImpl.decrypt(EncryptedAsicReaderImpl.java:127)
	at no.ks.fiks.io.asice.read.EncryptedAsicReaderImpl.lambda$decrypt$1(EncryptedAsicReaderImpl.java:53)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.bouncycastle.cms.CMSException: No content found.
	at org.bouncycastle.cms.CMSContentInfoParser.<init>(Unknown Source)
	at org.bouncycastle.cms.CMSEnvelopedDataParser.<init>(Unknown Source)
	at no.ks.kryptering.CMSKrypteringImpl.dekrypterData(CMSKrypteringImpl.java:150)
	... 7 more
```

**Forventet oppførsel**
Jeg mener at forventet oppførsel er at `isHarPayload` returnerer `false` når man har sendt inn en melding uten payload.

Sidenote relatert til logging av exceptionet: Jeg mener at det er voldsomt å logge alt dette når man uansett returnerer `null` for `mottattMelding.getDekryptertZipStream().getNextEntry()`. Det skaper støy i loggen, gjør at man kanskje silencer/starter å overse `KrypteringException` og situasjonen blir tross alt håndtert siden dette bibilioteket returnerer `null` fremfor at exceptionet propagerer. 
Dette fortjener dog kanskje et nytt exception. I førsteomgang vil det bli løst hvis `isHarPayload` oppfører seg korrekt.

**Forslag til mulig løsning**
Etter en rask titt i koden vil jeg tro at feilen er relatert til denne linjen:
https://github.com/ks-no/fiks-io-klient-java/blob/master/src/main/java/no/ks/fiks/io/client/AmqpHandler.java#L84
, da `m.getBody()` for en melding uten payload er en tom array (i.e `[]`).
Sjekken burde altså inkludere `m.getBody().length > 0`, mener jeg.

**Comment by johnksv** [comment]
Regner med at denne saken ble gjenåpnet ved en feil, @audunmeltzer . Tar meg friheten til å lukke den.
Takk for at dere løste denne.

**Comment by audunmeltzer** [comment]
Ville vente til release gikk igjennom. Ny klient versjon v2.0.6 skal være ute.
Takk for god tilbakemelding, og detaljert beskrivelse!
